### ISSUE TITLE
android 7.0 系统能给个支持吗

### ISSUE THREAD

**Issue by e-jlion** [lendylongli/qianghongbao#20]
android 7.0 系统能给个支持吗？
我 调试发现android 7.0下的微信在红包弹出来的界面上getRootInActiveWindow() 获得句柄方法为null 导致不会拆开红包问题，能帮忙解答怎么处理吗

**Comment by booldplx** [comment]
我的也是这个问题

**Comment by zyz002** [comment]
android 7.0 系统这个问题有什么办法解决吗？
