### ISSUE TITLE
现在几乎不能用了，主要有以下问题

### ISSUE THREAD

**Issue by xyxzfj** [lendylongli/qianghongbao#7]
1. 小米Note不能自动打开微信；
2. 手动打开微信进入的是第一个含[微信红包]的会话（可能是置顶的但不是最新的）；
3. 不会自动点击红包消息。

**Comment by leveychen** [comment]
这是小米的问题，我编译了一下 ，用公司测试机，魅族可以用，三星平板可用，nexus 可用。

**Comment by Shadowself** [comment]
现在微信的Ui 变了，把“拆红包” 的 button 设置成了“”；
还有就是id 变了 list = nodeInfo.findAccessibilityNodeInfosByViewId("com.tencent.mm:id/b43"); 改下就又能自动打开红包了，哈哈哈哈

**Comment by lendylongli** [comment]
现在不管拆红包界面变成什么id都不会影响，因为找不到关键文本，会遍历整个界面找button,所以依然可以拆红包

**Comment by Shadowself** [comment]
6666
